FROM peacemakr-go-sdk-dependencies as builder

ADD go.mod go.sum /go/src/github.com/peacemakr-io/peacemakr-go-sdk/
ADD ./pkg /go/src/github.com/peacemakr-io/peacemakr-go-sdk/pkg/
ADD ./example /go/src/github.com/peacemakr-io/peacemakr-go-sdk/example/

ENV GOPATH=/go

RUN go install github.com/peacemakr-io/peacemakr-go-sdk/example

FROM alpine:3.10

COPY --from=builder /go/src/github.com/peacemakr-io/peacemakr-go-sdk/pkg/crypto/lib /go/src/github.com/peacemakr-io/peacemakr-go-sdk/pkg/crypto/lib

WORKDIR /go/bin/
COPY --from=builder /go/bin /go/bin

CMD ./example
