FROM golang:1.12-alpine

RUN apk update && apk upgrade && apk add --no-cache git curl gcc musl-dev libbsd-dev ca-certificates && update-ca-certificates

ENV GOPATH=/go

ADD go.mod go.sum /go/src/github.com/notasecret/peacemakr-go-sdk/
ADD ./pkg /go/src/github.com/notasecret/peacemakr-go-sdk/pkg

RUN cd src/github.com/notasecret/peacemakr-go-sdk/. && GO111MODULE=on go mod vendor
