FROM 716293438869.dkr.ecr.us-east-2.amazonaws.com/corecrypto-dependencies0.0.2 as builder

FROM golang:1.11-alpine

COPY --from=builder /usr/local/lib/cmake /usr/local/lib/cmake
COPY --from=builder /usr/local/lib/libpeacemakr* /usr/local/lib/
COPY --from=builder /usr/local/include/peacemakr /usr/local/include/peacemakr
COPY --from=builder /usr/include/openssl /usr/include/openssl
COPY --from=builder /go/src /go/src

RUN apk update && apk upgrade && apk add --no-cache git curl gcc musl-dev libbsd-dev ca-certificates && update-ca-certificates

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

WORKDIR /go/.

ENV GOPATH=/go

ADD Gopkg.toml crypto.go crypto_impl.go utils.go /go/src/github.com/notasecret/peacemakr-go-sdk/
ADD ./utils /go/src/github.com/notasecret/peacemakr-go-sdk/utils/
ADD ./example /go/src/github.com/notasecret/peacemakr-go-sdk/example/
ADD ./crypto /go/src/github.com/notasecret/peacemakr-go-sdk/crypto/
ADD ./include /go/src/github.com/notasecret/peacemakr-go-sdk/include/
ADD ./generated /go/src/github.com/notasecret/peacemakr-go-sdk/generated/

RUN cd src/github.com/notasecret/peacemakr-go-sdk/.; dep ensure

