version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker version
      - run: $(aws ecr get-login --no-include-email --region us-east-2)
      - run: ls
      - run: ./generate-all-stubs.sh
      - run: docker-compose -f docker-compose-prod.yml pull
      - run: docker-compose -f docker-compose-prod.yml down || true
      - run: docker-compose -f docker-compose-prod.yml up -d
      - run: ./build-dependencies.sh 
      - run: docker-compose -f docker-compose-prod.yml down || true
      - run: ./build-binaries.sh
