on:
  push:
    branches:
      - master
  pull_request:

name: Build and Test

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get install musl-dev

      - name: Build and Test Go
        run: |
          go test ./pkg/...
